name: Deploy to heroku

# Run workflow on every push to master branch.
on:
  push:
    branches: [master]

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Release frontend to Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_FRONTEND_APP_NAME }}
          dockerfile_directory: ./frontend
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web
      # - name: Build, Push and Release backend to Heroku
      #   uses: gonuit/heroku-docker-deploy@v1.3.3
      #   with:
      #     email: ${{ secrets.HEROKU_EMAIL }}
      #     heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
      #     heroku_app_name: ${{ secrets.HEROKU_BACKEND_APP_NAME }}
      #     dockerfile_directory: ./backend
      #     dockerfile_name: Dockerfile
      #     docker_options: "--no-cache"
      #     process_type: web
          